app = 'pictshare-book'
primary_region = 'ams'

[build]
dockerfile = "apps/api/Dockerfile"

[env]
NODE_ENV = "production"

[http_service]
internal_port = 4000
force_https = true
min_machines_running = 1

processes = ['app']

[[vm]]
size = "shared-cpu-2x"
memory = "512mb"
processes = ["fly_app_release_command"]

[deploy]
strategy = "canary"
release_command = "bunx prisma migrate deploy --schema apps/api/prisma/schema.prisma"

[deploy.release_command_vm]
size = "shared-cpu-1x"
memory = "1gb"
