app = 'pictshare-book'
primary_region = 'fra'

[build]

[env]
NODE_ENV = "production"

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 256

[deploy]
strategy = "canary"
release_command = "npx prisma migrate deploy"
