app = 'pictshare-book'
primary_region = 'ams'

[build]

[env]
NODE_ENV = "production"

[http_service]
internal_port = 4000
force_https = true
min_machines_running = 1
processes = ['app']

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = 8192
processes = ["fly_app_release_command"]

[deploy]
strategy = "canary"
release_command = "bunx prisma migrate deploy"

[deploy.release_command_vm]
size = "shared-cpu-1x"
memory = "1gb"
